name: 'Upload a Build Artifact'
description: 'Upload a build artifact using azcopy'
inputs:
  name:
    description: 'Artifact name'
    default: 'artifact'
  path:
    description: 'A file, directory or wildcard pattern that describes what to upload'
    required: true
runs:
    using: 'composite'
    steps:
      - name: Dump runtime token
        id: dump-token
        uses: actions/github-script@v7
        with:
          script: return process.env.ACTIONS_RUNTIME_TOKEN
          result-encoding: string

      - name: Dump Results url
        id: dump-results
        uses: actions/github-script@v7
        with:
          script: return process.env.ACTIONS_RESULTS_URL.replace(/\/+$/g, '') 
          result-encoding: string

      - name: Upload artifact
        id: artifact
        shell: bash
        run: |
          echo "::add-mask::${{steps.dump-token.outputs.result}}"
          token=${{steps.dump-token.outputs.result}}
          scp=$(echo $token | jq -R 'split(".") | .[1] | @base64d | fromjson | .scp')
          workflowRunBackendId=$(echo $scp | awk -F " " '{print $2}' | awk -F ":" '{print $2}')
          workflowJobRunBackendId=$(echo $scp | awk -F " " '{print $2}' | awk -F ":" '{print $3}')
          payload="{\"workflowRunBackendId\": \"$workflowRunBackendId\", \"workflowJobRunBackendId\": \"$workflowJobRunBackendId\", \"name\": \"$ARTIFACT_NAME\", \"version\": \"4\"}"
          response=$(curl -sSf $SERVER_URL/twirp/github.actions.results.api.v1.ArtifactService/CreateArtifact --data "$payload" -H "Content-Type: application/json" -H "Authorization: Bearer $token")
          upload_url=$(echo $response | jq -r '.signed_upload_url')

          azcopy cp "${{ inputs.path }}" "$upload_url"

          response=$(curl -sSf $SERVER_URL/twirp/github.actions.results.api.v1.ArtifactService/FinalizeArtifact --data "$payload" -H "Content-Type: application/json" -H "Authorization: Bearer $token")
          echo "artifact_id=$(echo $response | jq -r '.artifact_id')" >> "$GITHUB_OUTPUT"
        env:
          ARTIFACT_NAME: ${{ inputs.name }}
          SERVER_URL: ${{steps.dump-results.outputs.result}}
